---
- hosts: all
  remote_user: vagrant
  tasks:
  - apt: pkg={{ item }} state=latest
    with_items:
      - apache2
      - libapache2-mod-wsgi
      - libapache2-mod-xsendfile
      - python-pip
      - python-virtualenv
    become: true
  - apache2_module: name={{ item }}
    with_items:
      - wsgi
      - xsendfile
    become: true
  - command: a2dissite 000-default
    become: true
  - template: src=xsendfile_example.vhost dest=/etc/apache2/sites-available/xsendfile_example.conf
    become: true
  - command: a2ensite xsendfile_example
    args:
      creates: /etc/apache2/sites-enabled/xsendfile_example.conf
    notify:
      - restart apache
    become: true
  - pip: name=pip virtualenv=/home/vagrant/venv
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
      become: true
